<?php

/**
 * @file
 * A light-weight, customizable lightbox plugin for jQuery 1.3
 */

use Drupal\Core\Template\Attribute;
use Drupal\Component\Serialization\Json;

/**
 * Prepares variables for Views HTML list templates.
 *
 * Default template: views-view-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A View object.
 */
function template_preprocess_views_view_flexslider(&$variables) {
  $handler  = $variables['view']->style_plugin;

  $list_classes = array('flexslides');
  if (!empty($variables['options']['flex_slider_clearfix'])) {
    $list_classes[] = "clearfix";
  }

  // Fetch classes from handler options.
  if ($handler->options['class']) {
    $list_classes = array_merge($list_classes, explode(' ', $handler->options['class']));
  }
  $list_classes = array_map('\Drupal\Component\Utility\Html::cleanCssIdentifier', $list_classes);
  // Initialize a new attribute class for $class.
  $variables['list']['attributes'] = new Attribute(array('class' => $list_classes));


  // Fetch wrapper classes from handler options.
  $wrapper_classes = array('flex-slider');
  if (!empty($handler->options['wrapper_class'])) {
    $wrapper_classes = array_merge($wrapper_classes, explode(' ', $handler->options['wrapper_class']));
  }
  #$variables['attributes']['class'] = array_map('\Drupal\Component\Utility\Html::cleanCssIdentifier', $wrapper_classes);
  $variables['attributes'] = new Attribute(array('class' => array_map('\Drupal\Component\Utility\Html::cleanCssIdentifier', $wrapper_classes)));

  $variables['list']['type'] = $handler->options['type'];

  // Flexslider configuration
  $variables['settings'] = array();
  foreach ($handler->options as $option_name => $option) {
    if (strpos($option_name, 'flexslide_') === 0 && !(is_string($option) && strlen($option) == 0)) {
      $variables['settings'][substr($option_name, 10)] = is_numeric($option) ? (int) $option : $option;
      unset($handler->options[$option_name]);
    }
  }
  $variables['attributes']['data-flexsliderconfig'] = Json::encode($variables['settings']);

  # $variables['#attached']['library'][] = 'flexslider_views/flexslider';
  $variables['#attached']['library'][] = 'flexslider_views/flexslider_views';

  template_preprocess_views_view_unformatted($variables);
}
